### ISSUE TITLE
pm example crashes

### ISSUE THREAD

**Issue by adventureloop** [NEAT-project/neat#245]
Running the example from policy/README.md crashes and leaves the pm in an infinite loop. It looks to be comparing incompatible types. Is this a bad set of config files, or should the pm gracefully handle this is some way?
   
     [ERROR]: Exception in callback _SelectorSocketTransport._read_ready()
     handle: <Handle _SelectorSocketTransport._read_ready()>
     Traceback (most recent call last):
       File "/usr/local/lib/python3.5/asyncio/events.py", line 125, in _run
         self._callback(*self._args)
       File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 680, in _read_ready
         keep_open = self._protocol.eof_received()
       File "./neatpmd.py", line 230, in eof_received
         candidates = process_request(self.request.strip())
       File "./neatpmd.py", line 148, in process_request
         for c in pib.lookup(candidate, tag=cand_id):
       File "/usr/home/tom/code/neat/policy/pib.py", line 284, in lookup
         if p.match_query(input_properties):
       File "/usr/home/tom/code/neat/policy/pib.py", line 112, in match_query
         if not self.match.items() <= input_properties.items():
       File "/usr/home/tom/code/neat/policy/policy.py", line 363, in __eq__
         return self & other
       File "/usr/home/tom/code/neat/policy/policy.py", line 358, in __and__
         return self._value & other._value
       File "/usr/home/tom/code/neat/policy/policy.py", line 184, in __and__
         new_set = [i for i in other.value if self.value[0] <= i <= self.value[1]]
       File "/usr/home/tom/code/neat/policy/policy.py", line 184, in <listcomp>
         new_set = [i for i in other.value if self.value[0] <= i <= self.value[1]]
     TypeError: unorderable types: float() <= str()

**Comment by adventureloop** [comment]
Well, 

It has stopped crashing. I have no idea what is going on.

**Comment by bozakov** [comment]
Weird - I wasn't able to reproduce the error. Please ping me if you run into the issue again.

**Comment by adventureloop** [comment]
Progress!

`request.json` is modified by socat if the pm doesn't crash. If I just use the request.json from the repository I can get the crash behaviour again.

**Comment by ruengeler** [comment]
I observed a similar problem when running the example. The program goes in an infinite loop.

### [ERROR]: Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 680, in _read_ready
    keep_open = self._protocol.eof_received()
  File "./neatpmd.py", line 242, in eof_received
    candidates = process_request(self.request.strip())
  File "./neatpmd.py", line 172, in process_request
    print(policy.term_separator('Top %d' % num_candidates))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-71: ordinal not in range(128)

**Comment by bozakov** [comment]
@adventureloop I updated the `socat` syntax and example JSON file which was using an outdated format. Does that solve the issue? @ruengeler Could you please check you're still getting the error?

**Comment by adventureloop** [comment]
I think that addresses it for me, I will leave it to  @ruengeler to respond and close.

**Comment by ruengeler** [comment]
I still get the infinite loop, which now ends with:

File "./neatpmd.py", line 141, in process_request
    print(policy.term_separator("processing request %d/%d" % (i + 1, len(requests)), offset=0, line_char='\u2500'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-63: ordinal not in range(128)

**Comment by bozakov** [comment]
@ruengeler this seems to be an issue with UTF-8 encoding in your terminal, I'll see if how can get around it.

**Comment by ruengeler** [comment]
I switched the parameters offset and line_char according to the signature in term_separator. 
print(policy.term_separator("processing request %d/%d" % (i + 1, len(requests)), line_char='-', offset=0))
Afterwards, it worked.
