### ISSUE TITLE
assertion failed when all connection attempts fail

### ISSUE THREAD

**Issue by perhurt** [NEAT-project/neat#257]
When trying to connect using a protocol (or protocols) not supported by the remote peer an internal assertion fails.

Steps to reproduce (example):

1.  Build the attached, SCTP-enabled, web client program ([client_sctp_http_get.c.zip](https://github.com/NEAT-project/neat/files/698970/client_sctp_http_get.c.zip))
2. Try to connect to a machine that does not support SCTP

coredump:
```
[New LWP 22554]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./client_sctp_http_get 192.168.60.28'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f87a73c0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f87a73c0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f87a73c202a in __GI_abort () at abort.c:89
#2  0x00007f87a73b8bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7f87a7772006 "handle->data", file=file@entry=0x7f87a7771ff0 "/tmp/neat/neat_core.c", line=line@entry=247, function=function@entry=0x7f87a7774020 <__PRETTY_FUNCTION__.24462> "neat_walk_cb") at assert.c:92
#3  0x00007f87a73b8c82 in __GI___assert_fail (assertion=0x7f87a7772006 "handle->data", file=0x7f87a7771ff0 "/tmp/neat/neat_core.c", line=247, function=0x7f87a7774020 <__PRETTY_FUNCTION__.24462> "neat_walk_cb") at assert.c:101
#4  0x00007f87a775bbbe in neat_walk_cb (handle=0x981ad0, arg=0x970420) at /tmp/neat/neat_core.c:247
#5  0x00007f87a7170cf7 in uv_walk () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#6  0x00007f87a775bc45 in neat_close_loop (nc=0x970420) at /tmp/neat/neat_core.c:262
#7  0x00007f87a775bca0 in neat_core_cleanup (nc=0x970420) at /tmp/neat/neat_core.c:274
#8  0x00007f87a775bd85 in neat_free_ctx (nc=0x970420) at /tmp/neat/neat_core.c:308
#9  0x0000000000401e3a in main (argc=2, argv=0x7ffda32976e8) at /tmp/neat/examples/client_sctp_http_get.c:249
(gdb) fr 4
#4  0x00007f87a775bbbe in neat_walk_cb (handle=0x981ad0, arg=0x970420) at /tmp/neat/neat_core.c:247
247	        assert(handle->data);
(gdb) list
242	    if (!uv_is_closing(handle)) {
243	        // If this assert triggers, then some handle is not being closed
244	        // correctly. A handle with a data pointer should already be closed
245	        // before this point since the next uv_close operation will not free
246	        // any handles. In other words, you have a memory leak.
247	        assert(handle->data);
248	
249	        neat_log(NEAT_LOG_DEBUG, "%s - closing handle", __func__);
250	        uv_close(handle, NULL);
251	    }
(gdb) 
```

**Comment by weinrank** [comment]
I'll have a look at it next week.
